In [ ]:
import numpy as np
# 1. Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.
vector = np.arange(1, 21)
print("Вектор (1-20):\n", vector)

Вектор (1-20):
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# 2. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.
matrix_1=np.ones((4, 4))
print("Матриця 4х4 з одиниць:\n", matrix_1)

Матриця 4х4 з одиниць:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.
matrix_2 = np.random.uniform(-1, 1, (5, 5))
print("Матриця 5x5 (-1 до 1):\n", matrix_2)

Матриця 5x5 (-1 до 1):
 [[ 0.57536191  0.30364308 -0.56200714 -0.5647907  -0.14346351]
 [ 0.41739135  0.534844   -0.90696873  0.2399129  -0.05006556]
 [-0.74312827 -0.90462089 -0.8567816  -0.96132627  0.3825719 ]
 [ 0.45617187 -0.49206152  0.76485787 -0.36877647  0.62405918]
 [-0.34598195 -0.66689347  0.00188343 -0.725447   -0.18631986]]


In [ ]:
# 4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
matrix_3 = np.random.rand(3, 3)
print("Матриця 3x3 (0 до 1):\n", matrix_3)

Матриця 3x3 (0 до 1):
 [[0.38885112 0.33161711 0.74265501]
 [0.98702045 0.94546993 0.39827696]
 [0.52781604 0.67062778 0.02545943]]


In [ ]:
# 5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20
# та виконайте на них поелементні операції додавання, віднімання та множення.
arr1 = np.random.randint(1, 21, 6)
arr2 = np.random.randint(1, 21, 6)

print("Масив 1:", arr1)
print("Масив 2:", arr2)
print("Додавання:", arr1 + arr2)
print("Віднімання:", arr1 - arr2)
print("Множення:", arr1 * arr2)

Масив 1: [ 4  8 20  1 10  1]
Масив 2: [12 17  3  3  1  6]
Додавання: [16 25 23  4 11  7]
Віднімання: [-8 -9 17 -2  9 -5]
Множення: [ 48 136  60   3  10   6]


In [ ]:
# 6. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.
mat1 = np.random.randint(1, 6, (3, 2))
mat2 = np.random.randint(1, 6, (2, 4))

product_matrix = np.dot(mat1, mat2) # Або mat1 @ mat2

print("Матриця 3x2:\n", mat1)
print("Матриця 2x4:\n", mat2)
print("Результат множення (3x4):\n", product_matrix)

In [ ]:
# 7. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
m_orig = np.random.rand(3, 3)
m_transposed = m_orig.T

print("Оригінальна матриця:\n", m_orig)
print("Транспонована матриця:\n", m_transposed)

Оригінальна матриця:
 [[0.35767485 0.85752439 0.96064425]
 [0.53114072 0.64829207 0.37782892]
 [0.20887485 0.98536824 0.34101349]]
Транспонована матриця:
 [[0.35767485 0.53114072 0.20887485]
 [0.85752439 0.64829207 0.98536824]
 [0.96064425 0.37782892 0.34101349]]


In [ ]:
# 8. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
m_a = np.random.randint(1, 11, (3, 3))
m_b = np.random.randint(1, 11, (3, 3))

print("Матриця A:\n", m_a)
print("Матриця B:\n", m_b)
print("Різниця (A - B):\n", m_a - m_b)

Матриця A:
 [[ 8 10  1]
 [10  3  8]
 [ 4  7  6]]
Матриця B:
 [[8 2 4]
 [1 2 1]
 [6 6 7]]
Різниця (A - B):
 [[ 0  8 -3]
 [ 9  1  7]
 [-2  1 -1]]


In [ ]:
# 9. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.
# Примітка: для матричного множення використовуємо np.dot або @, для поелементного - *
m_c = np.random.randint(-5, 6, (3, 3))
m_d = np.random.randint(-5, 6, (3, 3))

matrix_prod = np.dot(m_c, m_d)

print("Матриця C:\n", m_c)
print("Матриця D:\n", m_d)
print("Матричний добуток:\n", matrix_prod)

Матриця C:
 [[-5 -4 -3]
 [ 3  3  3]
 [-1  0  3]]
Матриця D:
 [[ 2  5  1]
 [-5  0 -4]
 [ 3  4  5]]
Матричний добуток:
 [[  1 -37  -4]
 [  0  27   6]
 [  7   7  14]]


In [ ]:
# 10. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1
# та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
m_last = np.random.uniform(-1, 1, (3, 3))
row_sums = np.sum(m_last, axis=1).reshape(-1, 1) # reshape робить з цього вектор-стовпчик

print("Матриця:\n", m_last)
print("Вектор-стовпчик сум рядків:\n", row_sums)

Матриця:
 [[ 0.28932448 -0.55451721  0.95472498]
 [ 0.70872837 -0.23845723  0.02255429]
 [-0.98719429 -0.00763088  0.19019368]]
Вектор-стовпчик сум рядків:
 [[ 0.68953225]
 [ 0.49282543]
 [-0.80463149]]
